development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: emprestei_dev
  pool: 5
  username: root
  password: 
  host: localhost
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: emprestei_test
  pool: 5
  username: root
  password: 
  host: localhost
  port: 3306
